# Generated by Django 5.0.6 on 2024-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_procent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
