# Generated by Django 5.0.6 on 2024-05-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zip_code',
        ),
    ]
